<?php

declare(strict_types=1);

namespace App\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the initial "user" table from the User entity.
 *
 * The SQL below was generated by "migrations:diff" against SQLite and matches
 * the schema produced by the ORM from the entity metadata. When switching to
 * MySQL or PostgreSQL, drop the database and regenerate a platform-specific
 * migration with "migrations:diff" (see the README).
 */
final class Version20260809122208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the user table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, '
            . 'username VARCHAR(48) NOT NULL, password VARCHAR(60) NOT NULL, '
            . 'email_address VARCHAR(255) NOT NULL, first_name VARCHAR(40) NOT NULL, '
            . 'last_name VARCHAR(40) NOT NULL)'
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649B08E074E ON user (email_address)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user');
    }
}
