<?php

declare(strict_types=1);

use App\Application\Actions\Health\HealthAction;
use App\Application\Actions\User\CreateUserAction;
use App\Application\Actions\User\DeleteUserAction;
use App\Application\Actions\User\ChangePasswordAction;
use App\Application\Actions\User\ListUsersAction;
use App\Application\Actions\User\UpdateUserAction;
use App\Application\Actions\User\ViewUserAction;
use OpenApi\Generator;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\App;
use Slim\Interfaces\RouteCollectorProxyInterface as Group;

// Set the "id" pattern
$id = '/{id:[0-9]+}';

return function (App $app) use ($id) {
    $app->options('/{routes:.*}', function (Request $request, Response $response) {
        // CORS Pre-Flight OPTIONS Request Handler
        return $response;
    });

    $app->get('/', function (Request $request, Response $response) {
        $response->getBody()->write('Hello world!');
        return $response;
    });

    $app->get('/health', HealthAction::class)->setName('health-check');

    $app->get('/docs.json', function (Request $request, Response $response) {
        $openApi = (new Generator())->generate([__DIR__ . '/../src']);

        if ($openApi === null) {
            return $response->withStatus(500, 'Unable to generate the OpenAPI specification.');
        }

        $response->getBody()->write($openApi->toJson());

        return $response->withHeader('Content-Type', 'application/json');
    });

    $app->get('/docs', function (Request $request, Response $response) {
        // Nonce generated by the security headers middleware; it must also
        // appear in the Content-Security-Policy header so the inline style
        // and script below are allowed to run.
        $nonce = $request->getAttribute('cspNonce');
        $nonceAttribute = is_string($nonce) && $nonce !== ''
            ? ' nonce="' . $nonce . '"'
            : '';

        $html = <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>API Documentation - Swagger UI</title>
            <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
            <style{$nonceAttribute}>
                html { box-sizing: border-box; overflow-y: scroll; }
                *, *::before, *::after { box-sizing: inherit; }
                body { margin: 0; background: #fafafa; }
            </style>
        </head>
        <body>
            <div id="swagger-ui"></div>
            <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
            <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-standalone-preset.js"></script>
            <script{$nonceAttribute}>
                window.onload = function () {
                    window.ui = SwaggerUIBundle({
                        url: '/docs.json',
                        dom_id: '#swagger-ui',
                        presets: [
                            SwaggerUIBundle.presets.apis,
                            SwaggerUIStandalonePreset,
                        ],
                        layout: 'StandaloneLayout',
                    });
                };
            </script>
        </body>
        </html>
        HTML;

        $response->getBody()->write($html);

        return $response->withHeader('Content-Type', 'text/html; charset=utf-8');
    });

    $app->group('/user', function (Group $group) use ($id) {
        $group->get('s', ListUsersAction::class)->setName('users-list');
        $group->post('', CreateUserAction::class)->setName('user-create');
        $group->get($id, ViewUserAction::class)->setName('user-view');
        $group->patch($id, UpdateUserAction::class)->setName('user-update');
        $group->patch($id . '/password', ChangePasswordAction::class)->setName('user-password');
        $group->delete($id, DeleteUserAction::class)->setName('user-delete');
    });
};
