<?php

declare(strict_types=1);

namespace Tests\Application\Middleware;

use App\Application\Middleware\ResponseCacheMiddleware;
use App\Application\Settings\Settings;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Server\RequestHandlerInterface as RequestHandler;
use Slim\Psr7\Response as SlimResponse;
use Symfony\Component\Cache\Adapter\ArrayAdapter;
use Tests\TestCase;

class ResponseCacheMiddlewareTest extends TestCase
{
    private const USERS_LIST_ROUTE = '/users';

    protected function setUp(): void
    {
        putenv('APP_HTTP_CACHE=1');

        $cacheDir = __DIR__ . '/../../../var/cache/http';

        if (is_dir($cacheDir)) {
            $this->removeDirectory($cacheDir);
        }
    }

    protected function tearDown(): void
    {
        putenv('APP_HTTP_CACHE=0');

        parent::tearDown();
    }

    private function removeDirectory(string $dir): void
    {
        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($items as $item) {
            $item->isDir() && !$item->isLink()
                ? rmdir($item->getPathname())
                : unlink($item->getPathname());
        }

        rmdir($dir);
    }

    public function testGetResponseIsCachedAcrossRequests()
    {
        $app = $this->getAppWithErrorHandling();

        $request = $this->createRequest('GET', self::USERS_LIST_ROUTE);

        $firstResponse = $app->handle($request);
        $secondResponse = $app->handle($request);

        $this->assertEquals(200, $firstResponse->getStatusCode());
        $this->assertSame('MISS', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('HIT', $secondResponse->getHeaderLine('X-Cache'));
        $this->assertSame((string) $firstResponse->getBody(), (string) $secondResponse->getBody());
    }

    public function testDifferentUrisAreCachedIndependently()
    {
        $app = $this->getAppWithErrorHandling();

        $listRequest = $this->createRequest('GET', self::USERS_LIST_ROUTE);
        $missingRequest = $this->createRequest('GET', '/user/999999999');

        $listResponse = $app->handle($listRequest);
        $missingResponse = $app->handle($missingRequest);

        $this->assertEquals(200, $listResponse->getStatusCode());
        $this->assertSame('MISS', $listResponse->getHeaderLine('X-Cache'));

        // Error responses are generated by the outer error handler, so they
        // never enter the cache layer and are never served as a cache HIT.
        $this->assertEquals(404, $missingResponse->getStatusCode());
        $this->assertNotSame('HIT', $missingResponse->getHeaderLine('X-Cache'));
    }

    public function testPostResponseIsNotCached()
    {
        $app = $this->getAppWithErrorHandling();

        $request = $this->createRequest('POST', '/users')
            ->withHeader('Content-Type', self::CONTENT_TYPE_JSON);
        $request->getBody()->write(json_encode([], JSON_THROW_ON_ERROR));

        $firstResponse = $app->handle($request);
        $secondResponse = $app->handle($request);

        $this->assertEquals(405, $firstResponse->getStatusCode());
        $this->assertNotSame('HIT', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertNotSame('HIT', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testRequestWithAuthorizationHeaderIsNotCached()
    {
        $app = $this->getAppWithErrorHandling();

        $request = $this->createRequest('GET', self::USERS_LIST_ROUTE, ['Authorization' => 'Bearer token']);

        $firstResponse = $app->handle($request);
        $secondResponse = $app->handle($request);

        $this->assertEquals(200, $firstResponse->getStatusCode());
        $this->assertSame('SKIP', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('SKIP', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testDisabledMiddlewareForwardsRequestWithoutXCacheHeader()
    {
        $middleware = new ResponseCacheMiddleware(new ArrayAdapter(), new Settings([
            'http_cache' => ['enabled' => false, 'ttl' => 60],
        ]));

        $response = $middleware->process($this->createRequest('GET', '/'), $this->staticHandler());

        $this->assertEquals(200, $response->getStatusCode());
        $this->assertFalse($response->hasHeader('X-Cache'));
    }

    public function testRequestWithCookieHeaderIsNotCached()
    {
        $middleware = new ResponseCacheMiddleware(new ArrayAdapter(), new Settings([
            'http_cache' => ['enabled' => true, 'ttl' => 60],
        ]));

        $request = $this->createRequest('GET', '/')->withHeader('Cookie', 'foo=bar');

        $firstResponse = $middleware->process($request, $this->staticHandler());
        $secondResponse = $middleware->process($request, $this->staticHandler());

        $this->assertSame('SKIP', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('SKIP', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testHeadRequestIsCachedAcrossRequests()
    {
        $middleware = new ResponseCacheMiddleware(new ArrayAdapter(), new Settings([
            'http_cache' => ['enabled' => true, 'ttl' => 60],
        ]));

        $request = $this->createRequest('HEAD', '/');

        $firstResponse = $middleware->process($request, $this->staticHandler());
        $secondResponse = $middleware->process($request, $this->staticHandler());

        $this->assertSame('MISS', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('HIT', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testResponseWithSetCookieIsNeverCached()
    {
        $middleware = new ResponseCacheMiddleware(new ArrayAdapter(), new Settings([
            'http_cache' => ['enabled' => true, 'ttl' => 60],
        ]));

        $handler = new class implements RequestHandler {
            public function handle(Request $request): Response
            {
                return (new SlimResponse(200))
                    ->withHeader('Set-Cookie', 'session=abc; HttpOnly');
            }
        };

        $request = $this->createRequest('GET', '/');

        $firstResponse = $middleware->process($request, $handler);
        $secondResponse = $middleware->process($request, $handler);

        $this->assertSame('MISS', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('MISS', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testRedirectResponseIsNeverCached()
    {
        $middleware = new ResponseCacheMiddleware(new ArrayAdapter(), new Settings([
            'http_cache' => ['enabled' => true, 'ttl' => 60],
        ]));

        $handler = new class implements RequestHandler {
            public function handle(Request $request): Response
            {
                return (new SlimResponse(302))->withHeader('Location', '/elsewhere');
            }
        };

        $request = $this->createRequest('GET', '/');

        $firstResponse = $middleware->process($request, $handler);
        $secondResponse = $middleware->process($request, $handler);

        $this->assertSame('MISS', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('MISS', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testHitResponseCarriesExactlyOneXCacheHeader()
    {
        $middleware = new ResponseCacheMiddleware(new ArrayAdapter(), new Settings([
            'http_cache' => ['enabled' => true, 'ttl' => 60],
        ]));

        $handler = $this->staticHandler();

        $request = $this->createRequest('GET', '/');

        $middleware->process($request, $handler);
        $hitResponse = $middleware->process($request, $handler);

        $this->assertSame('HIT', $hitResponse->getHeaderLine('X-Cache'));
        $this->assertSame(['HIT'], $hitResponse->getHeaders()['X-Cache']);
    }

    private function staticHandler(): RequestHandler
    {
        return new class implements RequestHandler {
            public function handle(Request $request): Response
            {
                return new SlimResponse(200);
            }
        };
    }
}
