<?php

declare(strict_types=1);

namespace Tests\Application\Middleware;

use Tests\TestCase;

class ResponseCacheMiddlewareTest extends TestCase
{
    protected function setUp(): void
    {
        putenv('APP_HTTP_CACHE=1');

        $cacheDir = __DIR__ . '/../../../var/cache/http';

        if (is_dir($cacheDir)) {
            $this->removeDirectory($cacheDir);
        }
    }

    protected function tearDown(): void
    {
        putenv('APP_HTTP_CACHE=0');

        parent::tearDown();
    }

    private function removeDirectory(string $dir): void
    {
        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($items as $item) {
            $item->isDir() && !$item->isLink()
                ? rmdir($item->getPathname())
                : unlink($item->getPathname());
        }

        rmdir($dir);
    }

    public function testGetResponseIsCachedAcrossRequests()
    {
        $app = $this->getAppWithErrorHandling();

        $request = $this->createRequest('GET', '/users');

        $firstResponse = $app->handle($request);
        $secondResponse = $app->handle($request);

        $this->assertEquals(200, $firstResponse->getStatusCode());
        $this->assertSame('MISS', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('HIT', $secondResponse->getHeaderLine('X-Cache'));
        $this->assertSame((string) $firstResponse->getBody(), (string) $secondResponse->getBody());
    }

    public function testDifferentUrisAreCachedIndependently()
    {
        $app = $this->getAppWithErrorHandling();

        $listRequest = $this->createRequest('GET', '/users');
        $missingRequest = $this->createRequest('GET', '/user/999999999');

        $listResponse = $app->handle($listRequest);
        $missingResponse = $app->handle($missingRequest);

        $this->assertEquals(200, $listResponse->getStatusCode());
        $this->assertSame('MISS', $listResponse->getHeaderLine('X-Cache'));

        // Error responses are generated by the outer error handler, so they
        // never enter the cache layer and are never served as a cache HIT.
        $this->assertEquals(404, $missingResponse->getStatusCode());
        $this->assertNotSame('HIT', $missingResponse->getHeaderLine('X-Cache'));
    }

    public function testPostResponseIsNotCached()
    {
        $app = $this->getAppWithErrorHandling();

        $request = $this->createRequest('POST', '/users')
            ->withHeader('Content-Type', self::CONTENT_TYPE_JSON);
        $request->getBody()->write(json_encode([], JSON_THROW_ON_ERROR));

        $firstResponse = $app->handle($request);
        $secondResponse = $app->handle($request);

        $this->assertEquals(405, $firstResponse->getStatusCode());
        $this->assertNotSame('HIT', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertNotSame('HIT', $secondResponse->getHeaderLine('X-Cache'));
    }

    public function testRequestWithAuthorizationHeaderIsNotCached()
    {
        $app = $this->getAppWithErrorHandling();

        $request = $this->createRequest('GET', '/users', ['Authorization' => 'Bearer token']);

        $firstResponse = $app->handle($request);
        $secondResponse = $app->handle($request);

        $this->assertEquals(200, $firstResponse->getStatusCode());
        $this->assertSame('SKIP', $firstResponse->getHeaderLine('X-Cache'));
        $this->assertSame('SKIP', $secondResponse->getHeaderLine('X-Cache'));
    }
}
